### ISSUE TITLE
Please make your roadmap link public shared during WiT Hackathon

### ISSUE THREAD

**Issue by RN0311** [Nidhikv473/ChatBot_Digipass#1]
Hey dear,

Just a brief intro : I'm WiT India Forum coordinator.
Issue : Your roadmap link and other docs supported link is not public, our jury will not be able to evaluate it unless it is public. Please resolve asap.

**Comment by RN0311** [comment]
Hey, I am now able to access your roadmap docs link. Apologies for inconvenience caused.

**Comment by Nidhikv473** [comment]
Hello Rashmi,

I can see that my repository is Public. Are you still not able to view my files? There are total of 7 files I have uploaded in that. Please let me know if you still cannot view any files from there.

Thanks
Nidhi

**Comment by RN0311** [comment]
I am able to now, dear.
